version: '3.9'

services:
  redis:
    image: redis
    ports:
      - '6379:6379'

  db:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./docker/postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: '${POSTGRESQL_USER}'
      POSTGRES_PASSWORD: '${POSTGRESQL_PASSWORD}'

volumes:
  postgres:
    driver: local
