export const abi = [
  {
    inputs: [
      { internalType: 'address', name: '_vault', type: 'address' },
      { internalType: 'address', name: '_ethAnchorRouter', type: 'address' },
      {
        internalType: 'contract AggregatorV3Interface',
        name: '_aUstToUstFeed',
        type: 'address',
      },
      { internalType: 'contract IERC20', name: '_ustToken', type: 'address' },
      { internalType: 'contract IERC20', name: '_aUstToken', type: 'address' },
      { internalType: 'address', name: '_owner', type: 'address' },
    ],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  { inputs: [], name: 'StrategyAmountZero', type: 'error' },
  { inputs: [], name: 'StrategyCallerNotManager', type: 'error' },
  { inputs: [], name: 'StrategyInvalidAUSTRate', type: 'error' },
  { inputs: [], name: 'StrategyNoAUSTReturned', type: 'error' },
  { inputs: [], name: 'StrategyNoUST', type: 'error' },
  { inputs: [], name: 'StrategyNotIVault', type: 'error' },
  { inputs: [], name: 'StrategyNotRunning', type: 'error' },
  { inputs: [], name: 'StrategyNothingRedeemed', type: 'error' },
  { inputs: [], name: 'StrategyOwnerCannotBe0Address', type: 'error' },
  { inputs: [], name: 'StrategyRouterCannotBe0Address', type: 'error' },
  { inputs: [], name: 'StrategyUnderlyingCannotBe0Address', type: 'error' },
  { inputs: [], name: 'StrategyYieldTokenCannotBe0Address', type: 'error' },
  { inputs: [], name: 'VaultAmountDoesNotMatchParams', type: 'error' },
  { inputs: [], name: 'VaultAmountLocked', type: 'error' },
  { inputs: [], name: 'VaultAmountTooLarge', type: 'error' },
  {
    inputs: [],
    name: 'VaultCannotComputeSharesWithoutPrincipal',
    type: 'error',
  },
  { inputs: [], name: 'VaultCannotDeposit0', type: 'error' },
  { inputs: [], name: 'VaultCannotDepositWhenYieldNegative', type: 'error' },
  { inputs: [], name: 'VaultCannotSponsor0', type: 'error' },
  { inputs: [], name: 'VaultCannotWithdrawMoreThanAvailable', type: 'error' },
  { inputs: [], name: 'VaultClaimPercentageCannotBe0', type: 'error' },
  { inputs: [], name: 'VaultClaimsDontAddUp', type: 'error' },
  { inputs: [], name: 'VaultDepositLocked', type: 'error' },
  { inputs: [], name: 'VaultDestinationCannotBe0Address', type: 'error' },
  { inputs: [], name: 'VaultInvalidInvestmentFee', type: 'error' },
  { inputs: [], name: 'VaultInvalidInvestpct', type: 'error' },
  { inputs: [], name: 'VaultInvalidLockPeriod', type: 'error' },
  { inputs: [], name: 'VaultInvalidMinLockPeriod', type: 'error' },
  { inputs: [], name: 'VaultInvalidPerformanceFee', type: 'error' },
  { inputs: [], name: 'VaultInvalidVault', type: 'error' },
  { inputs: [], name: 'VaultNoPerformanceFee', type: 'error' },
  { inputs: [], name: 'VaultNotAllowed', type: 'error' },
  { inputs: [], name: 'VaultNotDeposit', type: 'error' },
  { inputs: [], name: 'VaultNotEnoughFunds', type: 'error' },
  { inputs: [], name: 'VaultNotEnoughToRebalance', type: 'error' },
  { inputs: [], name: 'VaultNotOwnerOfDeposit', type: 'error' },
  { inputs: [], name: 'VaultNotSponsor', type: 'error' },
  { inputs: [], name: 'VaultNothingToDo', type: 'error' },
  { inputs: [], name: 'VaultOwnerCannotBe0Address', type: 'error' },
  { inputs: [], name: 'VaultStrategyHasInvestedFunds', type: 'error' },
  { inputs: [], name: 'VaultStrategyNotSet', type: 'error' },
  { inputs: [], name: 'VaultTreasuryCannotBe0Address', type: 'error' },
  { inputs: [], name: 'VaultUnderlyingCannotBe0Address', type: 'error' },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'operator',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'ustAmount',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'aUstAmount',
        type: 'uint256',
      },
    ],
    name: 'FinishDepositStable',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'operator',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'aUstAmount',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'ustAmount',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'underlyingAmount',
        type: 'uint256',
      },
    ],
    name: 'FinishRedeemStable',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'operator',
        type: 'address',
      },
      { indexed: true, internalType: 'uint256', name: 'idx', type: 'uint256' },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'underlyingAmount',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'ustAmount',
        type: 'uint256',
      },
    ],
    name: 'InitDepositStable',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'operator',
        type: 'address',
      },
      { indexed: true, internalType: 'uint256', name: 'idx', type: 'uint256' },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'aUstAmount',
        type: 'uint256',
      },
    ],
    name: 'InitRedeemStable',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'operatorFrom',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'operatorTo',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'uint256',
        name: 'newIdx',
        type: 'uint256',
      },
    ],
    name: 'RearrangeDepositOperation',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'operatorFrom',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'operatorTo',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'uint256',
        name: 'newIdx',
        type: 'uint256',
      },
    ],
    name: 'RearrangeRedeemOperation',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'bytes32', name: 'role', type: 'bytes32' },
      {
        indexed: true,
        internalType: 'bytes32',
        name: 'previousAdminRole',
        type: 'bytes32',
      },
      {
        indexed: true,
        internalType: 'bytes32',
        name: 'newAdminRole',
        type: 'bytes32',
      },
    ],
    name: 'RoleAdminChanged',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'bytes32', name: 'role', type: 'bytes32' },
      {
        indexed: true,
        internalType: 'address',
        name: 'account',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'sender',
        type: 'address',
      },
    ],
    name: 'RoleGranted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'bytes32', name: 'role', type: 'bytes32' },
      {
        indexed: true,
        internalType: 'address',
        name: 'account',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'sender',
        type: 'address',
      },
    ],
    name: 'RoleRevoked',
    type: 'event',
  },
  {
    inputs: [],
    name: 'DEFAULT_ADMIN_ROLE',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'MANAGER_ROLE',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'aUstToUstFeed',
    outputs: [
      {
        internalType: 'contract AggregatorV3Interface',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'aUstToken',
    outputs: [{ internalType: 'contract IERC20', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'depositOperationLength',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 'depositOperations',
    outputs: [
      { internalType: 'address', name: 'operator', type: 'address' },
      { internalType: 'uint256', name: 'amount', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'ethAnchorRouter',
    outputs: [
      { internalType: 'contract IEthAnchorRouter', name: '', type: 'address' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'idx', type: 'uint256' }],
    name: 'finishDepositStable',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'idx', type: 'uint256' }],
    name: 'finishRedeemStable',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes32', name: 'role', type: 'bytes32' }],
    name: 'getRoleAdmin',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes32', name: 'role', type: 'bytes32' },
      { internalType: 'address', name: 'account', type: 'address' },
    ],
    name: 'grantRole',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'hasAssets',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes32', name: 'role', type: 'bytes32' },
      { internalType: 'address', name: 'account', type: 'address' },
    ],
    name: 'hasRole',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'amount', type: 'uint256' }],
    name: 'initRedeemStable',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'invest',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'investedAssets',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'pendingDeposits',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'pendingRedeems',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'redeemOperationLength',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 'redeemOperations',
    outputs: [
      { internalType: 'address', name: 'operator', type: 'address' },
      { internalType: 'uint256', name: 'amount', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes32', name: 'role', type: 'bytes32' },
      { internalType: 'address', name: 'account', type: 'address' },
    ],
    name: 'renounceRole',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes32', name: 'role', type: 'bytes32' },
      { internalType: 'address', name: 'account', type: 'address' },
    ],
    name: 'revokeRole',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes4', name: 'interfaceId', type: 'bytes4' }],
    name: 'supportsInterface',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'ustToken',
    outputs: [{ internalType: 'contract IERC20', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'vault',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'withdrawAllToVault',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'amount', type: 'uint256' }],
    name: 'withdrawToVault',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
];
