name: Heroku Staging

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  HEROKU_SERVER_APP: ${{ secrets.HEROKU_SERVER_APP }}
  HEROKU_WORKER_APP: ${{ secrets.HEROKU_WORKER_APP }}

jobs:

  heroku-staging:
    
    steps:
      runs-on: ubuntu-latest
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Heroku login credentials
        run: |
          cat > ~/.netrc <<EOF
            machine api.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
            machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
          EOF
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
      
      - name: Worker - Add Heroku remote
        run: heroku git:remote --app $HEROKU_WORKER_APP
      
      - name: Worker - Push to Heroku
        run: git push https://git.heroku.com/$HEROKU_WORKER_APP.git HEAD:main

      - name: Server - Add Heroku remote
        run: heroku git:remote --app $HEROKU_SERVER_APP
      
      - name: Server - Push to Heroku
        run: git push https://git.heroku.com/$HEROKU_SERVER_APP.git HEAD:main