name: Heroku Staging

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  HEROKU_SERVER_APP: ${{ secrets.HEROKU_SERVER_APP }}
  HEROKU_WORKER_APP: ${{ secrets.HEROKU_WORKER_APP }}
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

jobs:

  heroku-staging:
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Worker - Add Heroku remote
        run: heroku git:remote --app $HEROKU_WORKER_APP
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      
      - name: Worker - Push to Heroku
        run: git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_WORKER_APP.git HEAD:main

      - name: Server - Add Heroku remote
        run: heroku git:remote --app $HEROKU_SERVER_APP
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      
      - name: Server - Push to Heroku
        run: git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_SERVER_APP.git HEAD:main
