name: Heroku Staging

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  worker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_WORKER_APP }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}

  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_SERVER_APP }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          